# Nixpacks configuration for Laravel on PHP 8.3 with required extensions.
# Nixpacks will detect PHP via composer.json and run Composer automatically,
# but we add explicit packages and a start command to be safe.

# Use Nix packages for PHP 8.3 + extensions and Composer
[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.intl",
  "php83Extensions.pdo_mysql",
  "php83Extensions.zip",
  "composer"
]

# Ensure a production-ready vendor install
[phases.install]
cmds = [
  "composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader"
]

# Optional: clear caches to avoid stale config between deploys
[phases.build]
cmds = [
  "php artisan package:discover || true",
  "php artisan config:clear || true",
  "php artisan route:clear || true",
  "php artisan view:clear || true"
]

# Start the HTTP server bound to the platform port
[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"
