# Nixpacks config for a Laravel app without Docker.
# Uses PHP 8.3 and installs required extensions.

[phases.setup]
# Install PHP 8.3, Composer, and needed PHP extensions.
# Note: extension names follow nixpkgs; adjust if your build log suggests a different name.
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "php83Extensions.intl",
  "php83Extensions.pdo_mysql",
  "php83Extensions.zip"
]

[phases.install]
# Install PHP dependencies
cmds = [
  "composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader"
]

[phases.build]
# Optional: compile caches for performance; these do not require DB
cmds = [
  "php artisan package:discover --ansi || true",
  "php artisan config:cache || true",
  "php artisan route:cache || true",
  "php artisan view:cache || true"
]

[start]
# Bind to Railway’s assigned port
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
